language: go
env:
  - GO111MODULE=on
go:
  - '1.11'
  - '1.12'
  - '1.13'
  - '1.14'
before_install:
  - go mod tidy
script:
  - go test ./... -v -cpu 2 -timeout 2m -race -cover -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)